recipebook/ledger/urls.py
from django.urls import path
from .views import recipeList, recipeEntry

urlpatterns = [
    path('recipes/list/', recipeList, name="recipeList"),
    path('recipe/<int:num>/', recipeEntry, name="recipeEntry"),
    ]

app_name = "ledger"

recipebook/recipebook/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("ledger.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home/', home_page, name="home"),
]

recipebook/ledger/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User    

class Ingredient(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return '{}'.format(self.name)

    def get_absolute_url(self):
        return '/ingredient/{}'.format(self.name)

    class Meta:
        ordering = ['name']
        unique_together = ['name']
        verbose_name = 'ingredient'
        verbose_name_plural = 'ingredients'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    bio = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    name = models.CharField(max_length=50)
    author = models.ForeignKey(Profile, on_delete = models.CASCADE, related_name = 'author', null=True)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)
    
    def get_absolute_url(self):
        return reverse("ledger:recipeEntry",kwargs={"num":int(self.name[7:])})

    def __str__(self):
        return '{}'.format(self.name)
    
    class Meta:
        ordering = ['name']
        unique_together = ['name']
        verbose_name = 'recipe'
        verbose_name_plural = 'recipes'


class RecipeIngredient(models.Model):
    quantity = models.CharField(max_length=50)
    ingredient = models.ForeignKey(Ingredient, on_delete = models.CASCADE, related_name = 'recipe')
    recipe = models.ForeignKey(Recipe, on_delete = models.CASCADE, related_name = 'ingredient')

recipebook/ledger/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.template import loader
from .models import Recipe, RecipeIngredient
from django.contrib.auth.decorators import login_required

@login_required
def recipeList(request):
    recipes = Recipe.objects.all()
    return render(request, "recipeList.html", {'recipes':recipes})

@login_required
def recipeEntry(request,num=-1):
    input_recipe_name = "Recipe "+str(num)
    involved_recipe = get_object_or_404(Recipe, name=input_recipe_name)
    recipeingredients = RecipeIngredient.objects.filter(recipe=involved_recipe)
    print(recipeingredients)
    
    return render(request, "recipeEntry.html", {'recipeingredients':recipeingredients, 'recipe': involved_recipe})

recipebook/recipebook/views.py
from django.shortcuts import render

def home_page(request):
	return render(request, 'home.html')

recipebook/ledger/templates/recipeEntry.html
{% extends 'base.html' %}
{% block title %}
	{{ recipe.name }}
{% endblock %}
{% block locator %}
	<p style="padding-top: 0.05rem; margin-bottom: -0.05rem; color: #BC7C33"> Now at: {{ recipe.name }}</p>
{% endblock %}
{% block content %}
	<div style="margin: auto; width: 85%; text-align: center; padding: 30px;">
		<ul>
			<h3>Entry: <b>{{ recipe.name }}</b></h3>
			Author: {{ recipe.author }}
			<br>
			Ingredients Required:
			<div style="margin: auto; width: 50%;">
				<ul style="text-align: left; padding: 15px; padding-left: 35%;">
					{% for item in recipeingredients %}
						<li style="margin: auto">
							{{ item.quantity }} {{ item.ingredient.name }}
						</li>
					{% endfor %}
				</ul>
			</div>
			<a href="{% url 'ledger:recipeList' %}">Return To List</a>
		</ul>
	</div>
{% endblock %}

recipebook/ledger/templates/recipeList.html
{% extends 'base.html' %}
{% block title %}Recipe List{% endblock %}
{% block locator %}
	<p style="padding-top: 0.05rem; margin-bottom: -0.05rem; color: #ABBA00"> Now at: Recipe List</p>
{% endblock %}
{% block content %}
	<div style="margin: auto; width: 85%; text-align: center; padding: 30px; padding-top: 30px;">
		<ul>
			<h3 style="color:green;">Available Recipes:</h3>
			<div style="margin: auto; width: 50%;">
				<ul style="text-align: left; padding: 15px; padding-left: 45%;">
					{% for recipe in recipes  %}
						<li>
							<a href="{{recipe.get_absolute_url}}"><b>{{ recipe.name }}</b></a>
						</li>
					{% endfor %}
				</ul>
			</div>
		</ul>
	</div>
{% endblock %}

recipebook/templates/base.html
<!DOCTYPE html>
<html lang="en-US">
<head>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	<nav class="navbar navbar-expand" style="background-color: grey;margin-bottom: 0rem;padding:-0.5rem">
		<div class="container-fluid">
			<div>
				<a href="{% url 'home' %}">
					<h2>
						<b style="color: blue;">Recipebook</b>
					</h2>
				</a>
			</div>
			<div>
				{% block locator %}{% endblock %}
			</div>
			<div>
				<ul class="navbar-nav">
					<li class="nav-item">
						{% if user.is_authenticated %}
							<form method="post" action="{% url 'logout' %}">
								{% csrf_token %}
								{{ form.as_p }}
								<button class="nav-link" type="submit">Logout</button>
							</form>
						{% else %}
						    <a href="{% url 'login' %}">Login</a>
						{% endif %}
					</li>
				</ul>
			</div>
		</div>
	</nav>
	<div id="content">
		{% block content %}{% endblock %}
	</div>
</body>
</html>

recipebook/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block locator %}
	<p style="padding-top: 0.05rem; margin-bottom: -0.05rem; color: #54BAAB"> Now at: Home</p>
{% endblock %}
{% block content %}
	<div style="margin: auto;width: 60%;text-align: center;padding: 30px;">
		<h1>Welcome Home!</h1>
		{% if user.is_authenticated %}
			<p>Feel free to explore the rest of this website, {{user.profile.name}}</p>
			<h4>Available Pages:</h4>
			<a href="{% url 'ledger:recipeList' %}">Recipe List</a>
		{% else %}
			<p>Make sure to login to gain access to the rest of this website</p>
		{% endif %}
	</div>
{% endblock %}